name: Prettier check for the React application
run-name: Pull request ${{github.event.number}} is being tested for good style
on:
  - push
  - pull_request
jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npx prettier --check ./src/
      - run: npx eslint src/**
